import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Job } from 'bullmq';
import { Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Product, ProductEmbedding } from '../entities';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

@Processor('reindex')
export class ReindexProcessor extends WorkerHost {
  private readonly logger = new Logger(ReindexProcessor.name);
  private s3: S3Client;

  constructor(
    @InjectRepository(Product)
    private readonly prodRepo: Repository<Product>,
    @InjectRepository(ProductEmbedding)
    private readonly embRepo: Repository<ProductEmbedding>,
  ) {
    super();
    this.s3 = new S3Client({
      endpoint: `http://${process.env.MINIO_ENDPOINT || 'localhost:9000'}`,
      region: 'us-east-1',
      credentials: {
        accessKeyId: process.env.MINIO_ACCESS_KEY || 'minioadmin',
        secretAccessKey: process.env.MINIO_SECRET_KEY || 'minioadmin',
      },
      forcePathStyle: true,
    });
  }

  async process(job: Job): Promise<void> {
    this.logger.log('Starting product reindex');

    const products = await this.prodRepo.find({ where: { isActive: true } });

    if (products.length === 0) {
      this.logger.log('Reindex: no active products found');
      return;
    }

    let indexed = 0;

    for (const product of products) {
      const existing = await this.embRepo.findOne({ where: { productId: product.id } });
      if (existing && existing.embeddingClip) {
        continue; // Already has valid embedding
      }

      try {
        const text = `${product.name}: ${product.description || ''}`;
        let embeddingClip: string | null = null;

        // If product has an image, download it for CLIP embedding
        if (product.imageUrl) {
          try {
            const key = product.imageUrl.split('/products/')[1];
            if (key) {
              const cmd = new GetObjectCommand({ Bucket: 'products', Key: key });
              const response = await this.s3.send(cmd);
              const body = response.Body;
              if (body) {
                await body.transformToByteArray();
              }

              // CLIP embedding will be generated by FastAPI on next catalog search
              // For now, we flag the product as having an available image
              embeddingClip = 'pending'; // Placeholder — CLIP runs in Python
            }
          } catch (err) {
            this.logger.warn(`Failed to process image for ${product.name}: ${err}`);
          }
        }

        // Generate text embedding via OpenAI API (or OpenRouter)
        let embeddingText: string | null = null;
        try {
          const { OpenAI } = await import('openai');
          const client = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
            baseURL: process.env.OPENROUTER_BASE_URL || undefined,
          });
          const response = await client.embeddings.create({
            model: process.env.OPENAI_EMBEDDING_MODEL || 'text-embedding-3-small',
            input: text,
          });
          embeddingText = JSON.stringify(response.data[0].embedding);
        } catch (err) {
          this.logger.warn(`Text embedding failed for ${product.name}: ${err}`);
        }

        const emb = new ProductEmbedding();
        emb.productId = product.id;
        emb.content = text;
        emb.mediaUrl = product.imageUrl ?? null;
        emb.embedding = embeddingText as string;
        emb.embeddingClip = embeddingClip as string;
        await this.embRepo.save(emb);
        indexed++;
        this.logger.debug(`Indexed product ${product.name}`);
      } catch (err) {
        this.logger.error(`Failed to index product ${product.name}: ${err}`);
      }
    }

    this.logger.log(`Reindex complete: ${indexed} products indexed`);
  }
}
