import { Processor, WorkerHost } from '@nestjs/bullmq';
import { Job } from 'bullmq';
import { Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Product, ProductEmbedding } from '../entities';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

@Processor('reindex')
export class ReindexProcessor extends WorkerHost {
  private readonly logger = new Logger(ReindexProcessor.name);
  private s3: S3Client;

  constructor(
    @InjectRepository(Product)
    private readonly prodRepo: Repository<Product>,
    @InjectRepository(ProductEmbedding)
    private readonly embRepo: Repository<ProductEmbedding>,
  ) {
    super();
    this.s3 = new S3Client({
      endpoint: `http://${process.env.MINIO_ENDPOINT || 'localhost:9000'}`,
      region: 'us-east-1',
      credentials: {
        accessKeyId: process.env.MINIO_ACCESS_KEY || 'minioadmin',
        secretAccessKey: process.env.MINIO_SECRET_KEY || 'minioadmin',
      },
      forcePathStyle: true,
    });
  }

  async process(job: Job): Promise<void> {
    this.logger.log('Starting product reindex');

    const products = await this.prodRepo.find({ where: { isActive: true } });

    if (products.length === 0) {
      this.logger.log('Reindex: no active products found');
      return;
    }

    // Filter out products that already have valid embeddings
    const productsToProcess = [];
    for (const product of products) {
      const existing = await this.embRepo.findOne({ where: { productId: product.id } });
      if (existing && existing.embeddingClip) {
        continue; // Already has valid embedding
      }
      productsToProcess.push(product);
    }

    if (productsToProcess.length === 0) {
      this.logger.log('Reindex complete: 0 products indexed (all up to date)');
      return;
    }

    // Prepare texts for batch embedding
    const textsToEmbed = productsToProcess.map(product => `${product.name}: ${product.description || ''}`);

    // Generate text embeddings in batch, chunking to avoid API limits
    let embeddings: string[] = [];
    const CHUNK_SIZE = 500;

    try {
      const { OpenAI } = await import('openai');
      const client = new OpenAI({
        apiKey: process.env.OPENAI_API_KEY,
        baseURL: process.env.OPENROUTER_BASE_URL || undefined,
      });

      for (let i = 0; i < textsToEmbed.length; i += CHUNK_SIZE) {
        const chunk = textsToEmbed.slice(i, i + CHUNK_SIZE);
        const response = await client.embeddings.create({
          model: process.env.OPENAI_EMBEDDING_MODEL || 'text-embedding-3-small',
          input: chunk,
        });
        const chunkEmbeddings = response.data.map(d => JSON.stringify(d.embedding));
        embeddings = embeddings.concat(chunkEmbeddings);
      }
    } catch (err) {
      this.logger.warn(`Batch text embedding failed: ${err}`);
      // Initialize with nulls to continue processing
      embeddings = new Array(productsToProcess.length).fill(null);
    }

    let indexed = 0;

    for (let i = 0; i < productsToProcess.length; i++) {
      const product = productsToProcess[i];
      const text = textsToEmbed[i];
      const embeddingText = embeddings[i];

      try {
        let embeddingClip: string | null = null;

        // If product has an image, download it for CLIP embedding
        if (product.imageUrl) {
          try {
            const key = product.imageUrl.split('/products/')[1];
            if (key) {
              const cmd = new GetObjectCommand({ Bucket: 'products', Key: key });
              const response = await this.s3.send(cmd);
              const body = response.Body;
              if (body) {
                await body.transformToByteArray();
              }

              // CLIP embedding will be generated by FastAPI on next catalog search
              // For now, we flag the product as having an available image
              embeddingClip = 'pending'; // Placeholder — CLIP runs in Python
            }
          } catch (err) {
            this.logger.warn(`Failed to process image for ${product.name}: ${err}`);
          }
        }

        const emb = new ProductEmbedding();
        emb.productId = product.id;
        emb.content = text;
        emb.mediaUrl = product.imageUrl ?? null;
        emb.embedding = embeddingText as string;
        emb.embeddingClip = embeddingClip as string;
        await this.embRepo.save(emb);
        indexed++;
        this.logger.debug(`Indexed product ${product.name}`);
      } catch (err) {
        this.logger.error(`Failed to index product ${product.name}: ${err}`);
      }
    }

    this.logger.log(`Reindex complete: ${indexed} products indexed`);
  }
}
